/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


package Liberarie;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author OMAR
 */
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import java.io.File;
import static javax.swing.Action.NAME;

public class FormPlus extends javax.swing.JFrame {
    User1 FUtama=new User1();
    final String AKSI_SELANJUTNYA;
    String sIdUser, sName, sAge, sSex, sAddress;
    public FormPlus(JFrame parent, String ACTION, String NOM) throws Exception {
        
        initComponents();
        
        System.out.println();
        AKSI_SELANJUTNYA = ACTION;
        sIdUser = "";
        sName = "";
        sAge = "";
        sSex = "";
        sAddress = "";
        String JudulJendela = "";
        
        JudulJendela = "Create new Data.";
        if (AKSI_SELANJUTNYA == "Form Change") {
            JudulJendela = "Modification of Data.";
            try {
                Statement st = Conex.conn.createStatement();
                String SQLEdit = "select * from user where id_user = '" + NAME + "' ";
                ResultSet rs = st.executeQuery(SQLEdit);
                rs.first();
                sIdUser = rs.getString(1);
                sName = rs.getString(2);
                sAge = rs.getString(3);
                sSex = rs.getString(4);
                sAddress = rs.getString(5);
                txtId.setEnabled(false);
            } catch (Exception e2) {
                System.out.println(e2);
            }
        }
        
        txtId.setText(sIdUser);
        txtName.setText(sName);
        txtAge.setText(sAge);
        txtSex.setText(sSex);
        txtAddress.setText(sAddress);
    }




    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtSex = new javax.swing.JTextField();
        btnBack = new komponenMakeOver.buttonMakeOver();
        buttonMakeOver6 = new komponenMakeOver.buttonMakeOver();
        buttonMakeOver8 = new komponenMakeOver.buttonMakeOver();
        btnSav = new komponenMakeOver.buttonMakeOver();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(153, 102, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("IdUser             :");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(50, 100, 110, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name             :");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(50, 130, 100, 14);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Age                :  ");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(50, 160, 120, 14);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sex   :");
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(50, 190, 120, 14);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address            :");
        jDesktopPane1.add(jLabel5);
        jLabel5.setBounds(50, 220, 120, 14);
        jDesktopPane1.add(txtAddress);
        txtAddress.setBounds(140, 220, 310, 20);
        jDesktopPane1.add(txtId);
        txtId.setBounds(140, 100, 310, 20);
        jDesktopPane1.add(txtName);
        txtName.setBounds(140, 130, 310, 20);
        jDesktopPane1.add(txtAge);
        txtAge.setBounds(140, 160, 310, 20);
        jDesktopPane1.add(txtSex);
        txtSex.setBounds(140, 190, 310, 20);

        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnBack);
        btnBack.setBounds(80, 280, 190, 40);

        buttonMakeOver6.setForeground(new java.awt.Color(255, 255, 255));
        buttonMakeOver6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jDesktopPane1.add(buttonMakeOver6);
        buttonMakeOver6.setBounds(-10, 70, 540, 10);

        buttonMakeOver8.setForeground(new java.awt.Color(255, 255, 255));
        buttonMakeOver8.setText("Registering and Modifying a User");
        buttonMakeOver8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        buttonMakeOver8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMakeOver8ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(buttonMakeOver8);
        buttonMakeOver8.setBounds(0, 0, 540, 80);

        btnSav.setForeground(new java.awt.Color(255, 255, 255));
        btnSav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/male_user.png"))); // NOI18N
        btnSav.setText("Save");
        btnSav.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnSav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnSav);
        btnSav.setBounds(280, 280, 180, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavActionPerformed
        String s1, s2, s3, s4, s5;
                    s1 = txtId.getText();
                    s2 = txtName.getText();
                    s3 = txtAge.getText();
                    s4 = txtSex.getText();
                    s5 = txtAddress.getText();
                    String SQLExecute;
                    if (AKSI_SELANJUTNYA == "Form Plus") {
                        SQLExecute = "insert into user values('" + s1 + "','" + s2 + "','" + s3 + "','" + s4 + "','" + s5 + "')";
                    } else {
                        SQLExecute = "update user set name = '" + s2 + "', age = '" + s3 + "', sex = '" + s4 + "', address = '" + s5 + "' where id_user = '" + s1 + "'";
                    }
                    try {
                    Statement stmt = Conex.conn.createStatement();
                    int i = stmt.executeUpdate(SQLExecute);
                    
                    System.out.println("Row Updated:" + i);
                    //this.dispose();
                    User1 a=new User1();
                    a.CariData(0, "");
                    } catch (Exception e1) {
                    //System.out.println("ERROR:" + e1);
                    JOptionPane.showMessageDialog(this, "The data could not be saved, make sure input data is not in the database\nClik OK à Continue!!", "Error !!", JOptionPane.WARNING_MESSAGE);

                }
    }
private String gambar(String id) {
        return User1.folder + File.separator + id.trim() + ".jpg";
    }
private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    this.dispose();
    User1 a=new User1();
    a.CariData(0, "");                                   
    }//GEN-LAST:event_btnSavActionPerformed

private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    this.dispose();
    User1 a = new User1();
    a.CariData(0, "");
}//GEN-LAST:event_btnBackActionPerformed

    private void buttonMakeOver8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMakeOver8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMakeOver8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        Conex conn =  new Conex();
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new FormPlus(null,null, null).show();
                } catch (Exception ex) {
                    Logger.getLogger(FormPlus.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private komponenMakeOver.buttonMakeOver btnBack;
    private komponenMakeOver.buttonMakeOver btnSav;
    private komponenMakeOver.buttonMakeOver buttonMakeOver6;
    private komponenMakeOver.buttonMakeOver buttonMakeOver8;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSex;
    // End of variables declaration//GEN-END:variables
}
