
package Liberarie;
import javax.swing.table.DefaultTableModel;
import java.awt.Canvas;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URL;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.util.*;
import java.sql.*;
import javax.swing.table.*;

/**
 *
 * @author OMAR
 */
public class Trans extends javax.swing.JFrame {

    public static String folder;
public static void cetak(String str) {
        System.out.println(str);
    }
public static String gambar(String id) {
        return folder + File.separator + id.trim() + ".jpg";
    }

    public Trans() {
        initComponents();
        
        folder = System.getProperty("user.dir") + File.separator + "images";
        //folder = getClass().getResource("").getFile().toString() + "images";
        cetak(folder);
        new File(folder).mkdir();
        
         ArrayList values = new ArrayList();

        // buat table 
        String[] colHeads = {"id_trans", "date", "id_user", "code_book"};
        int noOfRows = (values.size());
        int no = 0;
        
        //table.setBounds(20, 20, 350, 200);
        tabMode = new DefaultTableModel(null, colHeads);
        tblTrans.setModel(tabMode);
        CariData(0, "");
        ImageIcon gambar = new ImageIcon("./img/pb3.png");
    setIconImage(gambar.getImage());

   // cara kedua untuk merubah icon pada swing
    setIconImage(Toolkit.getDefaultToolkit().getImage("./img/pb3.png"));
    setDefaultCloseOperation(this.EXIT_ON_CLOSE);
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        buttonMakeOver7 = new komponenMakeOver.buttonMakeOver();
        buttonMakeOver6 = new komponenMakeOver.buttonMakeOver();
        btnBackReg = new komponenMakeOver.buttonMakeOver();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTrans = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(153, 102, 255));

        buttonMakeOver7.setForeground(new java.awt.Color(255, 255, 255));
        buttonMakeOver7.setText("Last Week Transaction Data");
        buttonMakeOver7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jDesktopPane1.add(buttonMakeOver7);
        buttonMakeOver7.setBounds(-10, 0, 520, 80);

        buttonMakeOver6.setForeground(new java.awt.Color(255, 255, 255));
        buttonMakeOver6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jDesktopPane1.add(buttonMakeOver6);
        buttonMakeOver6.setBounds(-10, 70, 550, 10);

        btnBackReg.setForeground(new java.awt.Color(255, 255, 255));
        btnBackReg.setText("Back");
        btnBackReg.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnBackReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackRegActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnBackReg);
        btnBackReg.setBounds(40, 330, 130, 40);

        tblTrans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTrans);

        jDesktopPane1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 110, 420, 200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackRegActionPerformed
        this.dispose();
        Home a = new Home();
        a.show();
}//GEN-LAST:event_btnBackRegActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        new PosteCentral(this);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        Conex conn = new Conex();
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Trans().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private komponenMakeOver.buttonMakeOver btnBackReg;
    private komponenMakeOver.buttonMakeOver buttonMakeOver6;
    private komponenMakeOver.buttonMakeOver buttonMakeOver7;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTrans;
    // End of variables declaration//GEN-END:variables

final DefaultTableModel tabMode;
   public void CariData(int IndexPencarian, String Parameter) {
        try {
            int row = tabMode.getRowCount();
            for (int i = 0; i < row; i++) {
                tabMode.removeRow(0);
            }
            String Kondisi = "";
            String SQLKondisi = "";
            switch (IndexPencarian) {
                case 0:
                    Kondisi = "id_trans";
                    break;
                case 1:
                    Kondisi = "date";
                    break;
                case 2:
                    Kondisi = "id_user";
                    break;
                case 3:
                    Kondisi = "code_book";
                    break;
            }
            if ((Kondisi != "") && (Parameter != "")) {
                SQLKondisi = " where " + Kondisi + " like '%" + Parameter + "%'";
            }

            Conex.conn = DriverManager.getConnection(Conex.Url, Conex.User, Conex.Password);
            Statement Update_st = Conex.conn.createStatement();
            String SQLSearch = "select * from transaction" + SQLKondisi;
            ResultSet Update_rs = Update_st.executeQuery(SQLSearch);
            while (Update_rs.next()) {
                Object[] data = {Update_rs.getString("id_trans"), Update_rs.getString("date"), Update_rs.getString("id_user"), Update_rs.getString("code_book")};
                tabMode.addRow(data);
                //
            }
        } catch (Exception e2) {
        //
        }

    }


}
